[package]
name = "Hdc10082Mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = "0.5.1"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"]}
paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust.git", branch = "master" }